// Code generated by protoc-gen-form. DO NOT EDIT.
// Source: configcenter.proto

package pb

import (
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	url "net/url"
	strconv "strconv"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*GetGroupRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetGroupResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*ConfigCenterGroups)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetGroupPropertiesRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetGroupPropertiesResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*ConfigCenterPropertyList)(nil)
var _ urlenc.URLValuesUnmarshaler = (*ConfigCenterProperty)(nil)
var _ urlenc.URLValuesUnmarshaler = (*SaveGroupPropertiesRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*SaveGroupPropertiesResponse)(nil)

// GetGroupRequest implement urlenc.URLValuesUnmarshaler.
func (m *GetGroupRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "tenantId":
				m.TenantId = vals[0]
			case "keyword":
				m.Keyword = vals[0]
			case "pageNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.PageNum = val
			case "pageSize":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.PageSize = val
			}
		}
	}
	return nil
}

// GetGroupResponse implement urlenc.URLValuesUnmarshaler.
func (m *GetGroupResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				if m.Data == nil {
					m.Data = &ConfigCenterGroups{}
				}
			case "data.total":
				if m.Data == nil {
					m.Data = &ConfigCenterGroups{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Data.Total = val
			}
		}
	}
	return nil
}

// ConfigCenterGroups implement urlenc.URLValuesUnmarshaler.
func (m *ConfigCenterGroups) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "total":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Total = val
			}
		}
	}
	return nil
}

// GetGroupPropertiesRequest implement urlenc.URLValuesUnmarshaler.
func (m *GetGroupPropertiesRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "tenantId":
				m.TenantId = vals[0]
			case "groupId":
				m.GroupId = vals[0]
			}
		}
	}
	return nil
}

// GetGroupPropertiesResponse implement urlenc.URLValuesUnmarshaler.
func (m *GetGroupPropertiesResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// ConfigCenterPropertyList implement urlenc.URLValuesUnmarshaler.
func (m *ConfigCenterPropertyList) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// ConfigCenterProperty implement urlenc.URLValuesUnmarshaler.
func (m *ConfigCenterProperty) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "key":
				m.Key = vals[0]
			case "value":
				m.Value = vals[0]
			case "source":
				m.Source = vals[0]
			}
		}
	}
	return nil
}

// SaveGroupPropertiesRequest implement urlenc.URLValuesUnmarshaler.
func (m *SaveGroupPropertiesRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "tenantId":
				m.TenantId = vals[0]
			case "groupId":
				m.GroupId = vals[0]
			}
		}
	}
	return nil
}

// SaveGroupPropertiesResponse implement urlenc.URLValuesUnmarshaler.
func (m *SaveGroupPropertiesResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.Data = val
			}
		}
	}
	return nil
}
