// Code generated by protoc-gen-form. DO NOT EDIT.
// Source: resource.proto

package pb

import (
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	url "net/url"
	strconv "strconv"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*CreateResourceRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*CreateResourceResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*ResourceCreateResult)(nil)
var _ urlenc.URLValuesUnmarshaler = (*DeleteResourceRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*DeleteResourceResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetRuntimeRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetRuntimeResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*MonitorRuntime)(nil)

// CreateResourceRequest implement urlenc.URLValuesUnmarshaler.
func (m *CreateResourceRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "engine":
				m.Engine = vals[0]
			case "uuid":
				m.Uuid = vals[0]
			case "plan":
				m.Plan = vals[0]
			case "az":
				m.Az = vals[0]
			case "callback":
				m.Callback = vals[0]
			}
		}
	}
	return nil
}

// CreateResourceResponse implement urlenc.URLValuesUnmarshaler.
func (m *CreateResourceResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				if m.Data == nil {
					m.Data = &ResourceCreateResult{}
				}
			case "data.id":
				if m.Data == nil {
					m.Data = &ResourceCreateResult{}
				}
				m.Data.Id = vals[0]
			case "data.createdAt":
				if m.Data == nil {
					m.Data = &ResourceCreateResult{}
				}
				m.Data.CreatedAt = vals[0]
			case "data.updateAt":
				if m.Data == nil {
					m.Data = &ResourceCreateResult{}
				}
				m.Data.UpdateAt = vals[0]
			case "data.status":
				if m.Data == nil {
					m.Data = &ResourceCreateResult{}
				}
				m.Data.Status = vals[0]
			}
		}
	}
	return nil
}

// ResourceCreateResult implement urlenc.URLValuesUnmarshaler.
func (m *ResourceCreateResult) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "id":
				m.Id = vals[0]
			case "createdAt":
				m.CreatedAt = vals[0]
			case "updateAt":
				m.UpdateAt = vals[0]
			case "status":
				m.Status = vals[0]
			}
		}
	}
	return nil
}

// DeleteResourceRequest implement urlenc.URLValuesUnmarshaler.
func (m *DeleteResourceRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "engine":
				m.Engine = vals[0]
			case "id":
				m.Id = vals[0]
			}
		}
	}
	return nil
}

// DeleteResourceResponse implement urlenc.URLValuesUnmarshaler.
func (m *DeleteResourceResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.Data = val
			}
		}
	}
	return nil
}

// GetRuntimeRequest implement urlenc.URLValuesUnmarshaler.
func (m *GetRuntimeRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "terminusKey":
				m.TerminusKey = vals[0]
			case "applicationId":
				m.ApplicationId = vals[0]
			case "runtimeName":
				m.RuntimeName = vals[0]
			case "runtimeId":
				m.RuntimeId = vals[0]
			}
		}
	}
	return nil
}

// GetRuntimeResponse implement urlenc.URLValuesUnmarshaler.
func (m *GetRuntimeResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
			case "data.terminusKey":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.TerminusKey = vals[0]
			case "data.projectId":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.ProjectId = vals[0]
			case "data.projectName":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.ProjectName = vals[0]
			case "data.applicationId":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.ApplicationId = vals[0]
			case "data.applicationName":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.ApplicationName = vals[0]
			case "data.workspace":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.Workspace = vals[0]
			case "data.runtimeId":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.RuntimeId = vals[0]
			case "data.runtimeName":
				if m.Data == nil {
					m.Data = &MonitorRuntime{}
				}
				m.Data.RuntimeName = vals[0]
			}
		}
	}
	return nil
}

// MonitorRuntime implement urlenc.URLValuesUnmarshaler.
func (m *MonitorRuntime) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "terminusKey":
				m.TerminusKey = vals[0]
			case "projectId":
				m.ProjectId = vals[0]
			case "projectName":
				m.ProjectName = vals[0]
			case "applicationId":
				m.ApplicationId = vals[0]
			case "applicationName":
				m.ApplicationName = vals[0]
			case "workspace":
				m.Workspace = vals[0]
			case "runtimeId":
				m.RuntimeId = vals[0]
			case "runtimeName":
				m.RuntimeName = vals[0]
			}
		}
	}
	return nil
}
