// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: resource.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"
	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*CreateResourceRequest)(nil)
var _ json.Unmarshaler = (*CreateResourceRequest)(nil)
var _ json.Marshaler = (*CreateResourceResponse)(nil)
var _ json.Unmarshaler = (*CreateResourceResponse)(nil)
var _ json.Marshaler = (*ResourceCreateResult)(nil)
var _ json.Unmarshaler = (*ResourceCreateResult)(nil)
var _ json.Marshaler = (*DeleteResourceRequest)(nil)
var _ json.Unmarshaler = (*DeleteResourceRequest)(nil)
var _ json.Marshaler = (*DeleteResourceResponse)(nil)
var _ json.Unmarshaler = (*DeleteResourceResponse)(nil)
var _ json.Marshaler = (*GetRuntimeRequest)(nil)
var _ json.Unmarshaler = (*GetRuntimeRequest)(nil)
var _ json.Marshaler = (*GetRuntimeResponse)(nil)
var _ json.Unmarshaler = (*GetRuntimeResponse)(nil)
var _ json.Marshaler = (*MonitorRuntime)(nil)
var _ json.Unmarshaler = (*MonitorRuntime)(nil)

// CreateResourceRequest implement json.Marshaler.
func (m *CreateResourceRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateResourceRequest implement json.Marshaler.
func (m *CreateResourceRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// CreateResourceResponse implement json.Marshaler.
func (m *CreateResourceResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateResourceResponse implement json.Marshaler.
func (m *CreateResourceResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ResourceCreateResult implement json.Marshaler.
func (m *ResourceCreateResult) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// ResourceCreateResult implement json.Marshaler.
func (m *ResourceCreateResult) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// DeleteResourceRequest implement json.Marshaler.
func (m *DeleteResourceRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// DeleteResourceRequest implement json.Marshaler.
func (m *DeleteResourceRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// DeleteResourceResponse implement json.Marshaler.
func (m *DeleteResourceResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// DeleteResourceResponse implement json.Marshaler.
func (m *DeleteResourceResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetRuntimeRequest implement json.Marshaler.
func (m *GetRuntimeRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetRuntimeRequest implement json.Marshaler.
func (m *GetRuntimeRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetRuntimeResponse implement json.Marshaler.
func (m *GetRuntimeResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetRuntimeResponse implement json.Marshaler.
func (m *GetRuntimeResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MonitorRuntime implement json.Marshaler.
func (m *MonitorRuntime) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MonitorRuntime implement json.Marshaler.
func (m *MonitorRuntime) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
