// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: resource.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateResourceRequest) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *CreateResourceResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *ResourceCreateResult) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *DeleteResourceRequest) Validate() error {
	return nil
}
func (this *DeleteResourceResponse) Validate() error {
	return nil
}
func (this *GetRuntimeRequest) Validate() error {
	return nil
}
func (this *GetRuntimeResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *MonitorRuntime) Validate() error {
	return nil
}
