// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Source: project.proto

package pb

import (
	context "context"
	transport "github.com/erda-project/erda-infra/pkg/transport"
	grpc1 "github.com/erda-project/erda-infra/pkg/transport/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion5

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
}

type projectServiceClient struct {
	cc grpc1.ClientConnInterface
}

func NewProjectServiceClient(cc grpc1.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/erda.msp.tenant.project.ProjectService/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/erda.msp.tenant.project.ProjectService/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, "/erda.msp.tenant.project.ProjectService/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations should embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
}

// UnimplementedProjectServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (*UnimplementedProjectServiceServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (*UnimplementedProjectServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedProjectServiceServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}

func RegisterProjectServiceServer(s grpc1.ServiceRegistrar, srv ProjectServiceServer, opts ...grpc1.HandleOption) {
	s.RegisterService(_get_ProjectService_serviceDesc(srv, opts...), srv)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erda.msp.tenant.project.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "project.proto",
}

func _get_ProjectService_serviceDesc(srv ProjectServiceServer, opts ...grpc1.HandleOption) *grpc.ServiceDesc {
	h := grpc1.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}

	_ProjectService_GetProjects_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.GetProjects(ctx, req.(*GetProjectsRequest))
	}
	var _ProjectService_GetProjects_info transport.ServiceInfo
	if h.Interceptor != nil {
		_ProjectService_GetProjects_info = transport.NewServiceInfo("erda.msp.tenant.project.ProjectService", "GetProjects", srv)
		_ProjectService_GetProjects_Handler = h.Interceptor(_ProjectService_GetProjects_Handler)
	}

	_ProjectService_CreateProject_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.CreateProject(ctx, req.(*CreateProjectRequest))
	}
	var _ProjectService_CreateProject_info transport.ServiceInfo
	if h.Interceptor != nil {
		_ProjectService_CreateProject_info = transport.NewServiceInfo("erda.msp.tenant.project.ProjectService", "CreateProject", srv)
		_ProjectService_CreateProject_Handler = h.Interceptor(_ProjectService_CreateProject_Handler)
	}

	_ProjectService_GetProject_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.GetProject(ctx, req.(*GetProjectRequest))
	}
	var _ProjectService_GetProject_info transport.ServiceInfo
	if h.Interceptor != nil {
		_ProjectService_GetProject_info = transport.NewServiceInfo("erda.msp.tenant.project.ProjectService", "GetProject", srv)
		_ProjectService_GetProject_Handler = h.Interceptor(_ProjectService_GetProject_Handler)
	}

	var serviceDesc = _ProjectService_serviceDesc
	serviceDesc.Methods = []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetProjectsRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(ProjectServiceServer).GetProjects(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _ProjectService_GetProjects_info)
				}
				if interceptor == nil {
					return _ProjectService_GetProjects_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.msp.tenant.project.ProjectService/GetProjects",
				}
				return interceptor(ctx, in, info, _ProjectService_GetProjects_Handler)
			},
		},
		{
			MethodName: "CreateProject",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(CreateProjectRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(ProjectServiceServer).CreateProject(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _ProjectService_CreateProject_info)
				}
				if interceptor == nil {
					return _ProjectService_CreateProject_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.msp.tenant.project.ProjectService/CreateProject",
				}
				return interceptor(ctx, in, info, _ProjectService_CreateProject_Handler)
			},
		},
		{
			MethodName: "GetProject",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetProjectRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(ProjectServiceServer).GetProject(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _ProjectService_GetProject_info)
				}
				if interceptor == nil {
					return _ProjectService_GetProject_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.msp.tenant.project.ProjectService/GetProject",
				}
				return interceptor(ctx, in, info, _ProjectService_GetProject_Handler)
			},
		},
	}
	return &serviceDesc
}
