// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: project.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"
	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*GetProjectsRequest)(nil)
var _ json.Unmarshaler = (*GetProjectsRequest)(nil)
var _ json.Marshaler = (*GetProjectsResponse)(nil)
var _ json.Unmarshaler = (*GetProjectsResponse)(nil)
var _ json.Marshaler = (*Project)(nil)
var _ json.Unmarshaler = (*Project)(nil)

// GetProjectsRequest implement json.Marshaler.
func (m *GetProjectsRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetProjectsRequest implement json.Marshaler.
func (m *GetProjectsRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetProjectsResponse implement json.Marshaler.
func (m *GetProjectsResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetProjectsResponse implement json.Marshaler.
func (m *GetProjectsResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Project implement json.Marshaler.
func (m *Project) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// Project implement json.Marshaler.
func (m *Project) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
