// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: microservice_scope.proto

package pb

import (
	context "context"
	transport "github.com/erda-project/erda-infra/pkg/transport"
	http "github.com/erda-project/erda-infra/pkg/transport/http"
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	http1 "net/http"
	strconv "strconv"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/transport/http" package it is being compiled against.
const _ = http.SupportPackageIsVersion1

// MicroserviceScopeServiceHandler is the server API for MicroserviceScopeService service.
type MicroserviceScopeServiceHandler interface {
	// GET /api/msp/scope/encrypt
	EncryptMicroserviceScope(context.Context, *EncryptMicroserviceScopeRequest) (*EncryptMicroserviceScopeResponse, error)
	// GET /api/msp/scope/decrypt
	DecryptMicroserviceScope(context.Context, *DecryptMicroserviceScopeRequest) (*DecryptMicroserviceScopeResponse, error)
}

// RegisterMicroserviceScopeServiceHandler register MicroserviceScopeServiceHandler to http.Router.
func RegisterMicroserviceScopeServiceHandler(r http.Router, srv MicroserviceScopeServiceHandler, opts ...http.HandleOption) {
	h := http.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}
	encodeFunc := func(fn func(http1.ResponseWriter, *http1.Request) (interface{}, error)) http.HandlerFunc {
		return func(w http1.ResponseWriter, r *http1.Request) {
			out, err := fn(w, r)
			if err != nil {
				h.Error(w, r, err)
				return
			}
			if err := h.Encode(w, r, out); err != nil {
				h.Error(w, r, err)
			}
		}
	}

	add_EncryptMicroserviceScope := func(method, path string, fn func(context.Context, *EncryptMicroserviceScopeRequest) (*EncryptMicroserviceScopeResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*EncryptMicroserviceScopeRequest))
		}
		var EncryptMicroserviceScope_info transport.ServiceInfo
		if h.Interceptor != nil {
			EncryptMicroserviceScope_info = transport.NewServiceInfo("erda.msp.scope.MicroserviceScopeService", "EncryptMicroserviceScope", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				var in EncryptMicroserviceScopeRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				params := r.URL.Query()
				if vals := params["projectId"]; len(vals) > 0 {
					val, err := strconv.ParseInt(vals[0], 10, 64)
					if err != nil {
						return nil, err
					}
					in.ProjectID = val
				}
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, EncryptMicroserviceScope_info)
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_DecryptMicroserviceScope := func(method, path string, fn func(context.Context, *DecryptMicroserviceScopeRequest) (*DecryptMicroserviceScopeResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*DecryptMicroserviceScopeRequest))
		}
		var DecryptMicroserviceScope_info transport.ServiceInfo
		if h.Interceptor != nil {
			DecryptMicroserviceScope_info = transport.NewServiceInfo("erda.msp.scope.MicroserviceScopeService", "DecryptMicroserviceScope", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				var in DecryptMicroserviceScopeRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				params := r.URL.Query()
				if vals := params["scopeId"]; len(vals) > 0 {
					in.ScopeID = vals[0]
				}
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, DecryptMicroserviceScope_info)
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_EncryptMicroserviceScope("GET", "/api/msp/scope/encrypt", srv.EncryptMicroserviceScope)
	add_DecryptMicroserviceScope("GET", "/api/msp/scope/decrypt", srv.DecryptMicroserviceScope)
}
