// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: adapter.proto

package pb

import (
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	url "net/url"
	strconv "strconv"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*GetAdapterRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetAdapterResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*AdapterStrategy)(nil)
var _ urlenc.URLValuesUnmarshaler = (*Adapters)(nil)

// GetAdapterRequest implement urlenc.URLValuesUnmarshaler.
func (m *GetAdapterRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// GetAdapterResponse implement urlenc.URLValuesUnmarshaler.
func (m *GetAdapterResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// AdapterStrategy implement urlenc.URLValuesUnmarshaler.
func (m *AdapterStrategy) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "displayName":
				m.DisplayName = vals[0]
			case "strategy":
				m.Strategy = vals[0]
			case "enable":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.Enable = val
			}
		}
	}
	return nil
}

// Adapters implement urlenc.URLValuesUnmarshaler.
func (m *Adapters) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "language":
				m.Language = vals[0]
			case "displayName":
				m.DisplayName = vals[0]
			}
		}
	}
	return nil
}
