// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: adapter.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"
	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*GetAdaptersRequest)(nil)
var _ json.Unmarshaler = (*GetAdaptersRequest)(nil)
var _ json.Marshaler = (*GetAdaptersResponse)(nil)
var _ json.Unmarshaler = (*GetAdaptersResponse)(nil)
var _ json.Marshaler = (*GetAdapterDocsRequest)(nil)
var _ json.Unmarshaler = (*GetAdapterDocsRequest)(nil)
var _ json.Marshaler = (*GetAdapterDocsResponse)(nil)
var _ json.Unmarshaler = (*GetAdapterDocsResponse)(nil)
var _ json.Marshaler = (*AdapterStrategy)(nil)
var _ json.Unmarshaler = (*AdapterStrategy)(nil)
var _ json.Marshaler = (*Adapters)(nil)
var _ json.Unmarshaler = (*Adapters)(nil)
var _ json.Marshaler = (*AdapterDocs)(nil)
var _ json.Unmarshaler = (*AdapterDocs)(nil)

// GetAdaptersRequest implement json.Marshaler.
func (m *GetAdaptersRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAdaptersRequest implement json.Marshaler.
func (m *GetAdaptersRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetAdaptersResponse implement json.Marshaler.
func (m *GetAdaptersResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAdaptersResponse implement json.Marshaler.
func (m *GetAdaptersResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetAdapterDocsRequest implement json.Marshaler.
func (m *GetAdapterDocsRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAdapterDocsRequest implement json.Marshaler.
func (m *GetAdapterDocsRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetAdapterDocsResponse implement json.Marshaler.
func (m *GetAdapterDocsResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAdapterDocsResponse implement json.Marshaler.
func (m *GetAdapterDocsResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// AdapterStrategy implement json.Marshaler.
func (m *AdapterStrategy) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// AdapterStrategy implement json.Marshaler.
func (m *AdapterStrategy) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Adapters implement json.Marshaler.
func (m *Adapters) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// Adapters implement json.Marshaler.
func (m *Adapters) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// AdapterDocs implement json.Marshaler.
func (m *AdapterDocs) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// AdapterDocs implement json.Marshaler.
func (m *AdapterDocs) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
