// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Source: adapter.proto

package pb

import (
	context "context"
	transport "github.com/erda-project/erda-infra/pkg/transport"
	grpc1 "github.com/erda-project/erda-infra/pkg/transport/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion5

// AdapterServiceClient is the client API for AdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterServiceClient interface {
	GetAdapters(ctx context.Context, in *GetAdapterRequest, opts ...grpc.CallOption) (*GetAdapterResponse, error)
}

type adapterServiceClient struct {
	cc grpc1.ClientConnInterface
}

func NewAdapterServiceClient(cc grpc1.ClientConnInterface) AdapterServiceClient {
	return &adapterServiceClient{cc}
}

func (c *adapterServiceClient) GetAdapters(ctx context.Context, in *GetAdapterRequest, opts ...grpc.CallOption) (*GetAdapterResponse, error) {
	out := new(GetAdapterResponse)
	err := c.cc.Invoke(ctx, "/erda.msp.apm.adapter.AdapterService/GetAdapters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServiceServer is the server API for AdapterService service.
// All implementations should embed UnimplementedAdapterServiceServer
// for forward compatibility
type AdapterServiceServer interface {
	GetAdapters(context.Context, *GetAdapterRequest) (*GetAdapterResponse, error)
}

// UnimplementedAdapterServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdapterServiceServer struct {
}

func (*UnimplementedAdapterServiceServer) GetAdapters(context.Context, *GetAdapterRequest) (*GetAdapterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdapters not implemented")
}

func RegisterAdapterServiceServer(s grpc1.ServiceRegistrar, srv AdapterServiceServer, opts ...grpc1.HandleOption) {
	s.RegisterService(_get_AdapterService_serviceDesc(srv, opts...), srv)
}

var _AdapterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erda.msp.apm.adapter.AdapterService",
	HandlerType: (*AdapterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "adapter.proto",
}

func _get_AdapterService_serviceDesc(srv AdapterServiceServer, opts ...grpc1.HandleOption) *grpc.ServiceDesc {
	h := grpc1.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}

	_AdapterService_GetAdapters_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.GetAdapters(ctx, req.(*GetAdapterRequest))
	}
	var _AdapterService_GetAdapters_info transport.ServiceInfo
	if h.Interceptor != nil {
		_AdapterService_GetAdapters_info = transport.NewServiceInfo("erda.msp.apm.adapter.AdapterService", "GetAdapters", srv)
		_AdapterService_GetAdapters_Handler = h.Interceptor(_AdapterService_GetAdapters_Handler)
	}

	var serviceDesc = _AdapterService_serviceDesc
	serviceDesc.Methods = []grpc.MethodDesc{
		{
			MethodName: "GetAdapters",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetAdapterRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(AdapterServiceServer).GetAdapters(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _AdapterService_GetAdapters_info)
				}
				if interceptor == nil {
					return _AdapterService_GetAdapters_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.msp.apm.adapter.AdapterService/GetAdapters",
				}
				return interceptor(ctx, in, info, _AdapterService_GetAdapters_Handler)
			},
		},
	}
	return &serviceDesc
}
