// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: greeter.proto

package pb

import (
	json "encoding/json"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*HelloRequest)(nil)
var _ json.Unmarshaler = (*HelloRequest)(nil)
var _ json.Marshaler = (*HelloResponse)(nil)
var _ json.Unmarshaler = (*HelloResponse)(nil)

// HelloRequest implement json.Marshaler.
func (m *HelloRequest) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// HelloRequest implement json.Marshaler.
func (m *HelloRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// HelloResponse implement json.Marshaler.
func (m *HelloResponse) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// HelloResponse implement json.Marshaler.
func (m *HelloResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
