// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: queue_usage.proto

package pb

import (
	json "encoding/json"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*QueueUsage)(nil)
var _ json.Unmarshaler = (*QueueUsage)(nil)
var _ json.Marshaler = (*QueueUsageItem)(nil)
var _ json.Unmarshaler = (*QueueUsageItem)(nil)

// QueueUsage implement json.Marshaler.
func (m *QueueUsage) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// QueueUsage implement json.Marshaler.
func (m *QueueUsage) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: false,
	}).Unmarshal(b, m)
}

// QueueUsageItem implement json.Marshaler.
func (m *QueueUsageItem) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// QueueUsageItem implement json.Marshaler.
func (m *QueueUsageItem) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: false,
	}).Unmarshal(b, m)
}
