// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: openapi.proto

package pb

import (
	url "net/url"
	strconv "strconv"

	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*OpenAPIOption)(nil)

// OpenAPIOption implement urlenc.URLValuesUnmarshaler.
func (m *OpenAPIOption) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "path":
				m.Path = vals[0]
			case "prefix":
				m.Prefix = vals[0]
			case "backend_prefix":
				m.BackendPrefix = vals[0]
			case "service":
				m.Service = vals[0]
			case "private":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.Private = val
			}
		}
	}
	return nil
}
