// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: accesskey.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"
	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*ListAccessKeysRequest)(nil)
var _ json.Unmarshaler = (*ListAccessKeysRequest)(nil)
var _ json.Marshaler = (*ListAccessKeysResponse)(nil)
var _ json.Unmarshaler = (*ListAccessKeysResponse)(nil)
var _ json.Marshaler = (*GetAccessKeysRequest)(nil)
var _ json.Unmarshaler = (*GetAccessKeysRequest)(nil)
var _ json.Marshaler = (*GetAccessKeysResponse)(nil)
var _ json.Unmarshaler = (*GetAccessKeysResponse)(nil)
var _ json.Marshaler = (*CreateAccessKeysRequest)(nil)
var _ json.Unmarshaler = (*CreateAccessKeysRequest)(nil)
var _ json.Marshaler = (*CreateAccessKeysResponse)(nil)
var _ json.Unmarshaler = (*CreateAccessKeysResponse)(nil)
var _ json.Marshaler = (*UpdateAccessKeysRequest)(nil)
var _ json.Unmarshaler = (*UpdateAccessKeysRequest)(nil)
var _ json.Marshaler = (*UpdateAccessKeysResponse)(nil)
var _ json.Unmarshaler = (*UpdateAccessKeysResponse)(nil)
var _ json.Marshaler = (*DeleteAccessKeysRequest)(nil)
var _ json.Unmarshaler = (*DeleteAccessKeysRequest)(nil)
var _ json.Marshaler = (*DeleteAccessKeysResponse)(nil)
var _ json.Unmarshaler = (*DeleteAccessKeysResponse)(nil)
var _ json.Marshaler = (*AccessKeysItem)(nil)
var _ json.Unmarshaler = (*AccessKeysItem)(nil)
var _ json.Marshaler = (*GenericEnum)(nil)
var _ json.Unmarshaler = (*GenericEnum)(nil)

// ListAccessKeysRequest implement json.Marshaler.
func (m *ListAccessKeysRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// ListAccessKeysRequest implement json.Marshaler.
func (m *ListAccessKeysRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListAccessKeysResponse implement json.Marshaler.
func (m *ListAccessKeysResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// ListAccessKeysResponse implement json.Marshaler.
func (m *ListAccessKeysResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetAccessKeysRequest implement json.Marshaler.
func (m *GetAccessKeysRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAccessKeysRequest implement json.Marshaler.
func (m *GetAccessKeysRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetAccessKeysResponse implement json.Marshaler.
func (m *GetAccessKeysResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetAccessKeysResponse implement json.Marshaler.
func (m *GetAccessKeysResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// CreateAccessKeysRequest implement json.Marshaler.
func (m *CreateAccessKeysRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateAccessKeysRequest implement json.Marshaler.
func (m *CreateAccessKeysRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// CreateAccessKeysResponse implement json.Marshaler.
func (m *CreateAccessKeysResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateAccessKeysResponse implement json.Marshaler.
func (m *CreateAccessKeysResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// UpdateAccessKeysRequest implement json.Marshaler.
func (m *UpdateAccessKeysRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// UpdateAccessKeysRequest implement json.Marshaler.
func (m *UpdateAccessKeysRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// UpdateAccessKeysResponse implement json.Marshaler.
func (m *UpdateAccessKeysResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// UpdateAccessKeysResponse implement json.Marshaler.
func (m *UpdateAccessKeysResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// DeleteAccessKeysRequest implement json.Marshaler.
func (m *DeleteAccessKeysRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// DeleteAccessKeysRequest implement json.Marshaler.
func (m *DeleteAccessKeysRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// DeleteAccessKeysResponse implement json.Marshaler.
func (m *DeleteAccessKeysResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// DeleteAccessKeysResponse implement json.Marshaler.
func (m *DeleteAccessKeysResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// AccessKeysItem implement json.Marshaler.
func (m *AccessKeysItem) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// AccessKeysItem implement json.Marshaler.
func (m *AccessKeysItem) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GenericEnum implement json.Marshaler.
func (m *GenericEnum) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GenericEnum implement json.Marshaler.
func (m *GenericEnum) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
