// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Source: todo.proto

package client

import (
	fmt "fmt"
	servicehub "github.com/erda-project/erda-infra/base/servicehub"
	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	pb "github.com/erda-project/erda-proto-go/monitor/pb"
	grpc1 "google.golang.org/grpc"
	reflect "reflect"
	strings "strings"
)

var dependencies = []string{
	"grpc-client@erda.monitor",
	"grpc-client",
}

type provider struct {
	client Client
}

func (p *provider) Init(ctx servicehub.Context) error {
	var conn grpc.ClientConnInterface
	for _, dep := range dependencies {
		c, ok := ctx.Service(dep).(grpc.ClientConnInterface)
		if ok {
			conn = c
			break
		}
	}
	if conn == nil {
		return fmt.Errorf("not found connector in (%s)", strings.Join(dependencies, ", "))
	}
	p.client = New(conn)
	return nil
}

var (
	clientsType           = reflect.TypeOf((*Client)(nil)).Elem()
	todoserviceClientType = reflect.TypeOf((*pb.TODOServiceClient)(nil)).Elem()
	todoserviceServerType = reflect.TypeOf((*pb.TODOServiceServer)(nil)).Elem()
)

func (p *provider) Provide(ctx servicehub.DependencyContext, args ...interface{}) interface{} {
	var opts []grpc1.CallOption
	for _, arg := range args {
		if opt, ok := arg.(grpc1.CallOption); ok {
			opts = append(opts, opt)
		}
	}
	switch ctx.Service() {
	case "erda.monitor-client":
		return p.client
	case "erda.monitor.TODOService":
		return &todoserviceWrapper{client: p.client.TODOService(), opts: opts}
	case "erda.monitor.TODOService.client":
		return p.client.TODOService()
	}
	switch ctx.Type() {
	case clientsType:
		return p.client
	case todoserviceClientType:
		return p.client.TODOService()
	case todoserviceServerType:
		return &todoserviceWrapper{client: p.client.TODOService(), opts: opts}
	}
	return p
}

func init() {
	servicehub.Register("erda.monitor-client", &servicehub.Spec{
		Services: []string{
			"erda.monitor.TODOService",
			"erda.monitor-client",
		},
		Types: []reflect.Type{
			clientsType,
			// client types
			todoserviceClientType,
			// server types
			todoserviceServerType,
		},
		OptionalDependencies: dependencies,
		Creator: func() servicehub.Provider {
			return &provider{}
		},
	})
}
