// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Sources: microservice_scope.proto

package client

import (
	fmt "fmt"
	servicehub "github.com/erda-project/erda-infra/base/servicehub"
	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	pb "github.com/erda-project/erda-proto-go/msp/scope/pb"
	grpc1 "google.golang.org/grpc"
	reflect "reflect"
	strings "strings"
)

var dependencies = []string{
	"grpc-client@erda.msp.scope",
	"grpc-client",
}

// +provider
type provider struct {
	client Client
}

func (p *provider) Init(ctx servicehub.Context) error {
	var conn grpc.ClientConnInterface
	for _, dep := range dependencies {
		c, ok := ctx.Service(dep).(grpc.ClientConnInterface)
		if ok {
			conn = c
			break
		}
	}
	if conn == nil {
		return fmt.Errorf("not found connector in (%s)", strings.Join(dependencies, ", "))
	}
	p.client = New(conn)
	return nil
}

var (
	clientsType                        = reflect.TypeOf((*Client)(nil)).Elem()
	microserviceScopeServiceClientType = reflect.TypeOf((*pb.MicroserviceScopeServiceClient)(nil)).Elem()
	microserviceScopeServiceServerType = reflect.TypeOf((*pb.MicroserviceScopeServiceServer)(nil)).Elem()
)

func (p *provider) Provide(ctx servicehub.DependencyContext, args ...interface{}) interface{} {
	var opts []grpc1.CallOption
	for _, arg := range args {
		if opt, ok := arg.(grpc1.CallOption); ok {
			opts = append(opts, opt)
		}
	}
	switch ctx.Service() {
	case "erda.msp.scope-client":
		return p.client
	case "erda.msp.scope.MicroserviceScopeService":
		return &microserviceScopeServiceWrapper{client: p.client.MicroserviceScopeService(), opts: opts}
	case "erda.msp.scope.MicroserviceScopeService.client":
		return p.client.MicroserviceScopeService()
	}
	switch ctx.Type() {
	case clientsType:
		return p.client
	case microserviceScopeServiceClientType:
		return p.client.MicroserviceScopeService()
	case microserviceScopeServiceServerType:
		return &microserviceScopeServiceWrapper{client: p.client.MicroserviceScopeService(), opts: opts}
	}
	return p
}

func init() {
	servicehub.Register("erda.msp.scope-client", &servicehub.Spec{
		Services: []string{
			"erda.msp.scope.MicroserviceScopeService",
			"erda.msp.scope-client",
		},
		Types: []reflect.Type{
			clientsType,
			// client types
			microserviceScopeServiceClientType,
			// server types
			microserviceScopeServiceServerType,
		},
		OptionalDependencies: dependencies,
		Creator: func() servicehub.Provider {
			return &provider{}
		},
	})
}
