// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

// oap ~ Observability Analysis Platform

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *KeyValue) Validate() error {
	if this.Value != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *KeyValueList) Validate() error {
	for _, item := range this.Values {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Values", err)
			}
		}
	}
	return nil
}
func (this *AnyValue) Validate() error {
	if oneOfNester, ok := this.GetValue().(*AnyValue_ArrayValue); ok {
		if oneOfNester.ArrayValue != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ArrayValue); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ArrayValue", err)
			}
		}
	}
	if oneOfNester, ok := this.GetValue().(*AnyValue_KvlistValue); ok {
		if oneOfNester.KvlistValue != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.KvlistValue); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("KvlistValue", err)
			}
		}
	}
	return nil
}
func (this *ArrayValue) Validate() error {
	for _, item := range this.Values {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Values", err)
			}
		}
	}
	return nil
}
func (this *Relation) Validate() error {
	return nil
}
