// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: expresion.proto

package pb

import (
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	url "net/url"
	strconv "strconv"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*GetExpresionRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*GetExpresionResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*Expresion)(nil)

// GetExpresionRequest implement urlenc.URLValuesUnmarshaler.
func (m *GetExpresionRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "type":
				m.Type = vals[0]
			}
		}
	}
	return nil
}

// GetExpresionResponse implement urlenc.URLValuesUnmarshaler.
func (m *GetExpresionResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// Expresion implement urlenc.URLValuesUnmarshaler.
func (m *Expresion) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "name":
				m.Name = vals[0]
			case "enable":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.Enable = val
			}
		}
	}
	return nil
}
