// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: meta.proto

package pb

import (
	json "encoding/json"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*ListMetricNamesRequest)(nil)
var _ json.Unmarshaler = (*ListMetricNamesRequest)(nil)
var _ json.Marshaler = (*ListMetricNamesResponse)(nil)
var _ json.Unmarshaler = (*ListMetricNamesResponse)(nil)
var _ json.Marshaler = (*ListMetricMetaRequest)(nil)
var _ json.Unmarshaler = (*ListMetricMetaRequest)(nil)
var _ json.Marshaler = (*ListMetricMetaResponse)(nil)
var _ json.Unmarshaler = (*ListMetricMetaResponse)(nil)
var _ json.Marshaler = (*ListMetricGroupsRequest)(nil)
var _ json.Unmarshaler = (*ListMetricGroupsRequest)(nil)
var _ json.Marshaler = (*ListMetricGroupsResponse)(nil)
var _ json.Unmarshaler = (*ListMetricGroupsResponse)(nil)
var _ json.Marshaler = (*GetMetricGroupRequest)(nil)
var _ json.Unmarshaler = (*GetMetricGroupRequest)(nil)
var _ json.Marshaler = (*GetMetricGroupResponse)(nil)
var _ json.Unmarshaler = (*GetMetricGroupResponse)(nil)
var _ json.Marshaler = (*MetricGroup)(nil)
var _ json.Unmarshaler = (*MetricGroup)(nil)
var _ json.Marshaler = (*GroupMetricMeta)(nil)
var _ json.Unmarshaler = (*GroupMetricMeta)(nil)
var _ json.Marshaler = (*MetricMeta)(nil)
var _ json.Unmarshaler = (*MetricMeta)(nil)
var _ json.Marshaler = (*NameDefine)(nil)
var _ json.Unmarshaler = (*NameDefine)(nil)
var _ json.Marshaler = (*TagDefine)(nil)
var _ json.Unmarshaler = (*TagDefine)(nil)
var _ json.Marshaler = (*FieldDefine)(nil)
var _ json.Unmarshaler = (*FieldDefine)(nil)
var _ json.Marshaler = (*ValueDefine)(nil)
var _ json.Unmarshaler = (*ValueDefine)(nil)
var _ json.Marshaler = (*Group)(nil)
var _ json.Unmarshaler = (*Group)(nil)
var _ json.Marshaler = (*MetaMode)(nil)
var _ json.Unmarshaler = (*MetaMode)(nil)
var _ json.Marshaler = (*TypeDefine)(nil)
var _ json.Unmarshaler = (*TypeDefine)(nil)
var _ json.Marshaler = (*Aggregation)(nil)
var _ json.Unmarshaler = (*Aggregation)(nil)
var _ json.Marshaler = (*Operation)(nil)
var _ json.Unmarshaler = (*Operation)(nil)

// ListMetricNamesRequest implement json.Marshaler.
func (m *ListMetricNamesRequest) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricNamesRequest implement json.Marshaler.
func (m *ListMetricNamesRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListMetricNamesResponse implement json.Marshaler.
func (m *ListMetricNamesResponse) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricNamesResponse implement json.Marshaler.
func (m *ListMetricNamesResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListMetricMetaRequest implement json.Marshaler.
func (m *ListMetricMetaRequest) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricMetaRequest implement json.Marshaler.
func (m *ListMetricMetaRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListMetricMetaResponse implement json.Marshaler.
func (m *ListMetricMetaResponse) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricMetaResponse implement json.Marshaler.
func (m *ListMetricMetaResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListMetricGroupsRequest implement json.Marshaler.
func (m *ListMetricGroupsRequest) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricGroupsRequest implement json.Marshaler.
func (m *ListMetricGroupsRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ListMetricGroupsResponse implement json.Marshaler.
func (m *ListMetricGroupsResponse) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ListMetricGroupsResponse implement json.Marshaler.
func (m *ListMetricGroupsResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetMetricGroupRequest implement json.Marshaler.
func (m *GetMetricGroupRequest) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// GetMetricGroupRequest implement json.Marshaler.
func (m *GetMetricGroupRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetMetricGroupResponse implement json.Marshaler.
func (m *GetMetricGroupResponse) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// GetMetricGroupResponse implement json.Marshaler.
func (m *GetMetricGroupResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MetricGroup implement json.Marshaler.
func (m *MetricGroup) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// MetricGroup implement json.Marshaler.
func (m *MetricGroup) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GroupMetricMeta implement json.Marshaler.
func (m *GroupMetricMeta) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// GroupMetricMeta implement json.Marshaler.
func (m *GroupMetricMeta) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MetricMeta implement json.Marshaler.
func (m *MetricMeta) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// MetricMeta implement json.Marshaler.
func (m *MetricMeta) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// NameDefine implement json.Marshaler.
func (m *NameDefine) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// NameDefine implement json.Marshaler.
func (m *NameDefine) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// TagDefine implement json.Marshaler.
func (m *TagDefine) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// TagDefine implement json.Marshaler.
func (m *TagDefine) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// FieldDefine implement json.Marshaler.
func (m *FieldDefine) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// FieldDefine implement json.Marshaler.
func (m *FieldDefine) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// ValueDefine implement json.Marshaler.
func (m *ValueDefine) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// ValueDefine implement json.Marshaler.
func (m *ValueDefine) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Group implement json.Marshaler.
func (m *Group) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// Group implement json.Marshaler.
func (m *Group) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MetaMode implement json.Marshaler.
func (m *MetaMode) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// MetaMode implement json.Marshaler.
func (m *MetaMode) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// TypeDefine implement json.Marshaler.
func (m *TypeDefine) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// TypeDefine implement json.Marshaler.
func (m *TypeDefine) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Aggregation implement json.Marshaler.
func (m *Aggregation) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// Aggregation implement json.Marshaler.
func (m *Aggregation) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Operation implement json.Marshaler.
func (m *Operation) MarshalJSON() ([]byte, error) {
	return (&protojson.MarshalOptions{
		UseProtoNames:   false,
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
	}).Marshal(m)
}

// Operation implement json.Marshaler.
func (m *Operation) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
