// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: metric.proto

package pb

import (
	transport "github.com/erda-project/erda-infra/pkg/transport"
	reflect "reflect"
)

// RegisterMetricServiceImp metric.proto
func RegisterMetricServiceImp(regester transport.Register, srv MetricServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterMetricServiceHandler(regester, MetricServiceHandler(srv), _ops.HTTP...)
	RegisterMetricServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.monitor.metric.MetricService",
	)
}

var (
	metricServiceClientType  = reflect.TypeOf((*MetricServiceClient)(nil)).Elem()
	metricServiceServerType  = reflect.TypeOf((*MetricServiceServer)(nil)).Elem()
	metricServiceHandlerType = reflect.TypeOf((*MetricServiceHandler)(nil)).Elem()
)

// MetricServiceClientType .
func MetricServiceClientType() reflect.Type { return metricServiceClientType }

// MetricServiceServerType .
func MetricServiceServerType() reflect.Type { return metricServiceServerType }

// MetricServiceHandlerType .
func MetricServiceHandlerType() reflect.Type { return metricServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		metricServiceClientType,
		// server types
		metricServiceServerType,
		// handler types
		metricServiceHandlerType,
	}
}
